<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE teiHeader [
    <!ELEMENT teiHeader (fileDesc, encodingDesc)>
    <!ELEMENT fileDesc (titleStmt, publicationStmt, sourceDesc)>
    <!ELEMENT titleStmt (title, author)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT publicationStmt (publisher, date)>
    <!ELEMENT publisher (#PCDATA)>
    <!ELEMENT date (#PCDATA)>
    <!ELEMENT sourceDesc (bibl+)>
    <!ELEMENT bibl (#PCDATA)>
    <!ELEMENT encodingDesc (editorialDecl)>
    <!ELEMENT editorialDecl (p)>
    <!ELEMENT p (#PCDATA | em)*>
    <!ELEMENT em (#PCDATA)>

    <!ATTLIST date type (publication | creation | revision) #REQUIRED>
    <!ATTLIST bibl type (book | article) #IMPLIED>

    <!ENTITY pubName "Université de Paris">
    <!ENTITY currentYear "2024">
]>

<teiHeader>
    <fileDesc>
        <titleStmt>
            <title>Évaluation XML TEI enrichie</title>
            <author>Jean Paul</author>
        </titleStmt>
        <publicationStmt>
            <publisher>&pubName;</publisher>
            <date type="publication">&currentYear;-11-25</date>
        </publicationStmt>
        <sourceDesc>
            <bibl type="book">Pierre Dupont, *Introduction au XML*, Éditions Techniques, 2020.</bibl>
            <bibl type="article">Marie Curie, "Les bases du XML TEI", *Revue Informatique*, vol. 15, 2019.</bibl>
        </sourceDesc>
    </fileDesc>
    <encodingDesc>
        <editorialDecl>
            <p>Ce fichier suit les règles définies par la DTD <em>evaluation.dtd</em>.</p>
        </editorialDecl>
    </encodingDesc>
</teiHeader>
