<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE conference [
    <!ELEMENT conference (titre, intervenant+, date, contenu)>
    <!ELEMENT titre (#PCDATA)>
    <!ELEMENT intervenant (#PCDATA | bio)*>
    <!ELEMENT bio (#PCDATA)>
    <!ELEMENT date EMPTY>
    <!ELEMENT contenu (session+)>
    <!ELEMENT session (presentation, note?)>
    <!ELEMENT presentation (resume+)>
    <!ELEMENT resume (#PCDATA)>
    <!ELEMENT note (#PCDATA)>

    <!ATTLIST intervenant id ID #REQUIRED>
    <!ATTLIST session id CDATA #REQUIRED theme CDATA #REQUIRED>
    <!ATTLIST presentation duree CDATA #REQUIRED langue CDATA "fr">

    <!ENTITY org "Centre International de Recherche">
    <!ENTITY pub "Revue des Innovations Technologiques">
]>

<conference>
    <titre>Conférence sur les Avancées en Technologie</titre>
    <intervenant id="i1">Dr. Clara Martin <bio>(Chercheuse senior au &org;)</bio></intervenant>
    <intervenant id="i2">Prof. Éric Lambert</intervenant>
    <intervenant id="i3">Mme. Sophie Durand <bio>(Coordinatrice à &pub;)</bio></intervenant>
    <date/>
    <contenu>
        <session id="s1" theme="Robots Humanoïdes">
            <presentation duree="40min" langue="fr">
                <resume>Discussion sur les robots humanoïdes par Dr. Clara Martin.</resume>
                <resume>Des articles connexes ont été publiés dans la &pub; en 2022.</resume>
            </presentation>
            <note>Session introduite par Prof. Éric Lambert.</note>
        </session>
        <session id="s2" theme="Technologies Vertes">
            <presentation duree="30min" langue="en">
                <resume>Étude des innovations technologiques dans le secteur des énergies renouvelables.</resume>
            </presentation>
        </session>
        <session id="s3" theme="Blockchain et Sécurité">
            <presentation duree="50min">
                <resume>Présentation de Mme. Sophie Durand sur les applications de la blockchain.</resume>
            </presentation>
        </session>
    </contenu>
</conference>
